config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/enroll' => 'enrollments#new'
  post 'webcam/login' => 'sessions#create_webcam'
  post '/add_user' => 'authorized_users#create'
  delete '/remove_user' => 'authorized_users#delete'

  resources :enrollments, only: [:create, :new]
  resources :dashboard, only: [:index]
  resources :apps, only: [:new, :create, :show, :update, :destroy]
  namespace :api do
    namespace :v1 do
        resources :authenticate, controller: 'app_authentications'
        resources :users, only: [:index]
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorize
  before_action :enrolled?

  def index
    @apps = current_user.apps.sort_by { |app| app.name.downcase }
    @authentications = current_user.authentications.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end
  
end

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <div class="panel panel-primary">

        <div class="panel-heading">
          Facial Recognition based login and authorization dashboard
        </div>
        <div class="panel-body">
          <p><b>From here you can:</b></p>
          <ul>
            <li> Manage your Apps and Devices authenticating through our service</li>
            <li>See which apps and devices you are authorized on</li>
            <li>See a log of details about your succesful authentications</li>
            <li>Are you having issues not being recognized? Creating additional enrollments can improve the accuracy of the facial recognition. <%= link_to 'Add additional enrollments here', enroll_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <%= render partial: 'layouts/app_index_table.html.erb' %>
  <%= render partial: 'layouts/authentications_table.html.erb' %>
  <%= render partial: 'layouts/authorized_apps_table.html.erb' %>

</div>