config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/enroll' => 'enrollments#new'
  post 'webcam/login' => 'sessions#create_webcam'
  post '/add_user' => 'authorized_users#create'
  delete '/remove_user' => 'authorized_users#delete'

  resources :enrollments, only: [:create, :new]
  resources :dashboard, only: [:index]
  resources :apps, only: [:new, :create, :show, :update, :destroy]
  namespace :api do
    namespace :v1 do
        resources :authenticate, controller: 'app_authentications'
        resources :users, only: [:index]
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :enrolled?

  def index
    if current_user
      redirect_to dashboard_index_path
    end
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="panel panel-primary">

        <div class="panel-heading">
          Facial Recognition based login and authorization
        </div>
        <div class="panel-body">
          <p><b>This site serves as a GUI for a user authentication and authorization system based on facial recognition.</b></p>
          <p>IOT devices with a camera can send a photo of a user to the API to authenticate</p>
        </div>
      </div>
    </div>
    <% if !current_user %>
    <div class="col-sm-4">
      <div class="panel panel-danger">

        <div class="panel-heading">
          Sign Up Now!
        </div>
        <div class="panel-body">
          <h1>Signup Here!</h1>

            <%= form_for :user, url: '/users' do |f| %>

              <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
              <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
              <%= f.text_field :email, class: 'form-control', placeholder: 'email' %>
              <%= f.password_field :password, class: 'form-control', placeholder: 'password' %>
              <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'confirm password' %>
              <%= f.submit "Sign up!", class: 'btn btn-primary' %>

            <% end %>
        </div>
        <div class="panel-footer">
          If you already have an acount <%= link_to 'Login Here', login_path %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>