config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/enroll' => 'enrollments#new'
  post 'webcam/login' => 'sessions#create_webcam'
  post '/add_user' => 'authorized_users#create'
  delete '/remove_user' => 'authorized_users#delete'

  resources :enrollments, only: [:create, :new]
  resources :dashboard, only: [:index]
  resources :apps, only: [:new, :create, :show, :update, :destroy]
  namespace :api do
    namespace :v1 do
        resources :authenticate, controller: 'app_authentications'
        resources :users, only: [:index]
    end
  end

end

app/views/layouts/_app_documentation.html.erb
<div class="row">
  <div class="col-md-10">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2>Docs: How to use the API with your app or device</h2>
      </div>
      <div class="panel-body">
        <div class="">
          <h4>How it works</h4>
          <p>When you register an app or device you are creating a way for this website to recognize your particular app, and which specific users are allowed to authenticate through it.</p><br>
          <p>The <b>confidence</b> setting determines how strict the facial recognition alogrithm will be when determining a match. A default value of 70 is our preference.</p><br>
          <p>The <b>Name</b> of your app/device will be displayed on your dashboard, and will be shown to users when they authenticate through your app/device</p>
          <p>To <b>authorize users</b> you will need the email address that they registered on this site with. Once your app has been created you can go to the <b>Manage authorized users and settings page</b> link on the dashboard. Once on the management page, type the user's email address into the <b>User Email</b> field and click on add user. </p>
          <p>Users will now be able to be recognized by your app or device. To remove a user from your app/device simpy click <b>Remove User Authentication</b> link next to their photo.</p>
          <p>Users must be specifically added by your app to be identified by the API. A user that is registered on this site, but not on your app, WILL NOT return a succesful authentication and identification through the API.</p>

        </div>
        <hr>
        <div class="">
          <h4>Authentication endpoint URL</h4>
          <p><b>'<%= request.base_url %>/api/v1/authenticate'</b></p>
        </div>
        <hr>
        <div class="">
          <h4>Requests to the API</h4>
          <p>In the header include: <b>'Content-Type: application/json
            '</b></p>
          <p>The body should be sent as a JSON payload in the following format: </p>
            <p><code>{'app_key': [app key generated after creating new app], 'image': [image as base64 jpeg string OR url for hosted image]}</code></p>

            <% if !@app.app_key.blank? %>
              <p><b>The key for this app is: <%= @app.app_key %></b> </p>
            <% else %>
              <p><b>The key for this app will be generated after submitting.</b> It will be visible on the dashboard or on the management page for the app</p>
            <% end %>
        </div>
        <hr>
        <div class="">
          <h4>Responses from the API</h4>
          <p><b>The API will respond with one of two responses</b></p>
          <p><b>For a SUCCESSFULL identification and authentication the response will be in JSON format in the body:</b></p>
          <p><code>{
              "authenticated": true,
              "user": {
                  "name": "[user's first name]",
                  "email": "[user's email]"
              }
          }</code></p><br>
          <p><b>For an UNSUCCESSFULL identification and authentication the response will be in JSON format in the body:</b></p>
          <p><code>{
              "authenticated": false,
              "error": "Unable to find a face that matched an authorized user"
          }</code></p><br>
        </div>

      </div>
    </div>

  </div>
</div>

app/views/layouts/_app_index_table.html.erb
<div class="row">
  <div class="col-10 panel panel-success">
    <div class="panel-heading">
      Apps and Devices that you own
    </div>
    <div class="panel-body">
      <p><%= link_to 'Create New App', new_app_path %></p>
      <table class="table table-striped">
        <thead>
          <th>App Name</th>
          <th>App Key</th>
          <th>Registered Users</th>
          <th>Confidence Threshold</th>
          <th></th>
        </thead>
          <tbody>
            <% @apps.each do |app| %>
              <tr>
                <td><%= app.name %></td>
                <td><%= app.app_key %></td>
                <td><%= app.users_count %></td>
                <td><%= (app.min_confidence * 100).round %></td>
                <td><%= link_to 'Manage authorized users and settings', app_path(app) %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_authentications_table.html.erb
<div class="row">
  <div class="col-10 panel panel-success">
    <div class="panel-heading">
      Succesful Authentications on Your Account
    </div>
    <div class="panel-body">
      <table class="table table-striped" id="authentications-table">
        <thead>
          <th>App Name</th>
          <th>Date</th>
          <th>Image</th>
        </thead>
          <tbody>
            <% @authentications.each do |authentication| %>
              <tr>
                <td><%= authentication.app.name %></td>
                <td><%= authentication.created_at %></td>
                <td><img src="<%= authentication.image  %>" style="width:90px ;"></td>

              </tr>
            <% end %>
          </tbody>
          <%= will_paginate @authentications %>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_authorized_apps_table.html.erb
<div class="row">
  <div class="col-10 panel panel-success">
    <div class="panel-heading">
      Apps and Devices that you have been authorized to use
    </div>
    <div class="panel-body">

      <table class="table table-striped" id="authorized-apps">
        <thead>
          <th>App Name</th>
          <th>Registered Users</th>
        </thead>
          <tbody>
            <% current_user.authorizations.each do |app| %>
              <tr>
                <td><%= app.name %></td>
                <td><%= app.users_count %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Re-Cognition</title>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<div class="">

  <nav class="navbar navbar-toggleable navbar-inverse navbar-static-top" id='Navbar'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/dashboard">Recognizer</a>
    </div>
    <div class="collapse navbar-collapse navbar-right" >
        <ul class="nav navbar-nav">
          <% if !current_user %>
            <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          <% end %>
          <% if current_user %>
            <li> <a href="<%= dashboard_index_path %>">DashBoard</a> </li>
            <li> <a href="">Welcome <%= current_user.first_name %></a> </li>
            <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
          <% end %>
        </ul>
    </div>
  </nav>
</div>

<div class="flashes">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <% value.each do |value| %>
        <%= value %><br>
      <% end %>
    </div>
  <% end if !flash.empty? %>
</div>
<%= yield %>

</body>
</html>